cms/urls.py
from django.urls import path, include

from django.contrib.auth.views import LoginView
from . import views

app_name = 'cms'

urlpatterns =[
	path('', views.IndexView.as_view(), name='home'),
	path('closed/',views.ClosedIndexView.as_view(), name = "closed"),
	path('accounts/', include('django.contrib.auth.urls'), name='login'),
	path('create-incident/', views.CreateIncidentView.as_view(),name='create-incident'),
	path('case/<int:pk>/', views.DetailCase.as_view(), name='case'),
	path('order/by_<condition>', views.IndexView.as_view(), name='order'),
	path('view-map/', views.mapview, name='view-map'),
  	path('send-message/<int:pk>/', views.MessageCreateView.as_view(), name = 'send_message'),
    path('succesSMS/', views.SuccessSMSView.as_view(), name = 'success_sms'),
]

cmssite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
	path('', views.home),
    path('admin/', admin.site.urls),
    path('cms/', include('cms.urls'))
]

cms/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Assistance(models.Model):
	number = models.CharField(
		max_length=8)
	name = models.CharField(
		max_length=50)

	def __str__(self):
		return self.name
	
class Comment(models.Model):
        Message = models.CharField(max_length = 200, default = "Run")

        def __str__(self):
                return self.Message
class Incident(models.Model):
	Fire = 'FIR'
	Haze = 'HAZ'
	Bird = 'BIR'
	Tsunami = 'TSU'
	Aftershock = 'AFT'
	Terrorist = 'TER'

	INCIDENT_TYPE_CHOICES = (
		(Fire,'Fire outbreak'),
		(Haze, 'Haze'),
		(Bird, 'Bird flu outbreak'),
		(Tsunami, 'Tsunami'),
		(Aftershock, 'Earthquake Aftershock'),
		(Terrorist, 'Terrorist Activity')
	)
	id = models.AutoField(primary_key=True)
	
	submitter = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		null=True)

	caller = models.CharField(
		max_length=50,
		default='Anonymous')

	message = models.CharField(
		max_length=100,
		default='All is good')

	mobile_number = models.CharField(
		max_length = 15,
		default = '0000 0000')

	incident_type = models.CharField(
		max_length=3,
		choices=INCIDENT_TYPE_CHOICES,
		)

	incident_date = models.DateTimeField('date incident happens',
											auto_now_add=True)

	assistance_type = models.ForeignKey(
		Assistance,
		on_delete=models.CASCADE)

	severity = models.IntegerField(default=1,
		choices=(
			(1,'1'),
			(2,'2'),
			(3,'3'),
			(4,'4'),
			(5,'5'),
			))

	location = models.TextField(default ='Singapore')

	is_closed = models.BooleanField(default=False)

	incident_closed_date = models.DateTimeField(null=True)

	lat = models.FloatField(null=True)
	long = models.FloatField(null=True)

	class Meta:
		ordering = ["-incident_date"]

cms/forms.py
from django import forms
from .models import Incident, Comment
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin



class IncidentForm(forms.ModelForm):
	street_name = forms.CharField()
	apartment_number = forms.CharField()
	postal_code = forms.CharField()


	class Meta:
		model = Incident
		fields = (
			'incident_type',
			'assistance_type',
			'severity',
			'caller',
			'mobile_number',
		)

	def clean_postal_code(self):
		postal_code = self.cleaned_data['postal_code']
		try:
			code = int(postal_code)
			if code // 100000 == 0 or code//100000 > 9:
				raise forms.ValidationError('Postal code is a 6 digits number')
		except ValueError:
			raise forms.ValidationError('Postal code is a 6 digits number')

class MessageForm(PopRequestMixin, CreateUpdateAjaxMixin,forms.ModelForm):
        class Meta:
                model = Incident
                fields = ('message',)

cms/views.py
'''
TODO
filter
view all cases (closed and open)
form caller, submitter
closed by
'''


from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from bootstrap_modal_forms.mixins import PassRequestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth import logout
from django.urls import reverse_lazy

from .models import Incident
from .forms import IncidentForm, MessageForm
from .location import getCoordinates
from .filters import IncidentFilter
from API.weather import getPSI, getWeather
import json
from django.contrib.auth.decorators import login_required
from cms.TelegramBotAPI import tele
from cms.TwitterAPI import tweets
import requests
# Create your views here.

class MessageCreateView(PassRequestMixin, SuccessMessageMixin,
		     generic.CreateView):

	
	model = Incident
	template_name = 'cms/Message.html'
	def get(self, request, pk):
		form = MessageForm()
		return render(request, self.template_name, {'form': form})

	def post(self, request,pk):
		form = MessageForm(request.POST)
		obj = Incident.objects.get(pk=pk)
		if form.is_valid():
			Message = form.cleaned_data['message']
			obj.message = Message
			postal_code = obj.location[-6:]
			obj.save()
			tele(postal_code,Message)
			tweets(postal_code,Message)
			return render(request,'cms/success_social_media.html')
		return render(request, self.template_name, {'form': form})

class SuccessSMSView(TemplateView):

	template_name = 'cms/success_sms.html'	

class IndexView(LoginRequiredMixin, generic.ListView):
	model = Incident

	context_object_name = 'incident_list'
	template_name = 'cms/index.html'

	conditions ={
		"severity": "severity",
		"date" : "incident_date__date"
	}

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['filter'] = IncidentFilter(self.request.GET,queryset=Incident.objects.filter(is_closed = False))
		return context

class ClosedIndexView(LoginRequiredMixin, generic.ListView):
	model = Incident

	context_object_name = 'incident_list'
	template_name = 'cms/closedindex.html'

	conditions ={
		"severity": "severity",
		"date" : "incident_date__date"
	}

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['filter'] = IncidentFilter(self.request.GET,queryset=Incident.objects.filter(is_closed = True))
		return context



class CreateIncidentView(LoginRequiredMixin, generic.TemplateView):
	template_name = 'cms/createincident.html'

	def get(self, request):
		form = IncidentForm()
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = IncidentForm(request.POST)
		if form.is_valid():
			incident = form.save(commit=False)
			location = form.cleaned_data['street_name'] + " " + form.cleaned_data['apartment_number'] +" " + form.data['postal_code']
			incident.location = location
			incident.submitter = request.user
			incident.lat, incident.long = getCoordinates(int(form.data['postal_code']))
			incident.save()
			requests.post('https://textbelt.com/text', {
			  'phone': '+6597512690',
			  'message': '*insert text here* ' + 'DEFAULT MESSAGE IF FREE',
			  'key': 'textbelt',    #textbelt is default key
			                        #new key will be given when paid.
			    })
			return HttpResponseRedirect(reverse('cms:success_sms'))
		return render(request, self.template_name, {'form': form})

class DetailCase(PassRequestMixin, SuccessMessageMixin,generic.DetailView):
	template_name = 'cms/detail_case.html'
	model = Incident
	print("form")
	def post(self, request, pk):
		print("valid")
		self.object = self.get_object()
		self.object.is_closed = True
		self.object.incident_closed_date = timezone.now()
		self.object.save()	
		messages.info(request, "Case " + str(self.object.id) + " has been closed successfully")
		return render(request, "cms/closed_confirm.html")
	print("invalid")

#@login_required
def mapview(request):

	psi_north = getPSI('north')
	psi_south = getPSI('south')
	psi_east = getPSI('east')
	psi_west = getPSI('west')
	psi_central = getPSI('central')
	weather = getWeather()

	data = []
	for incident in Incident.objects.all():
		if(incident.is_closed==False and incident.lat!=None and incident.long!=None):
			data.append({"lat":incident.lat, "lng":incident.long})
	json_data = json.dumps(data)

	context = {
		'psi_north': psi_north,
		'psi_south': psi_south,
		'psi_east': psi_east,
		'psi_west': psi_west,
		'psi_central': psi_central,
		'weather_north': weather['North'],
		'weather_south': weather['South'],
		'weather_east': weather['East'],
		'weather_west': weather['West'],
		'weather_central': weather['Central'],
		'data': json_data,
	}
	
	return render(request, 'cms/view-map.html', context=context)

cmssite/views.py
from django.shortcuts import redirect


def home(request):
	return redirect('cms:home')

cms/templates/cms/closed_confirm.html
{% include "cms/nav bar.html" %}

<!DOCTYPE html>
<html>
<head>
	<title>CMS</title>
</head>
<body>
	<div class ="container">
		<div class="jumbotron text-center">
      	<h1 class="display-4">Thank you for your patience</h1>
      	<p class="lead">You have succesfully closed the case</p>
      	<a class="btn btn-primary btn-lg" href="{% url 'cms:home' %}">Return home</a>
 		</div>
	</div>
</body>
</html>

cms/templates/cms/closedindex.html
{% include "cms/nav bar.html" %}
{% block content %}
{% load tz %}
{% load static %}
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
	<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
	<script src="{% static 'cms/js/jquery.bootstrap.modal.forms.js' %}"></script>

</head>
		

<style>
	input[type=date]
	{
		background-color: #6C757D;
		border-radius: 5px;
		color: #FFFFFF;
		height: 35.5px;
		position: relative;

		font-size: 17px;
		right: 110px;
	}

	input[type=date]::-webkit-inner-spin-button {display: none;}
	input[type=date]::-webkit-calendar-picker-indicator {
				background-color: #6C757D;
	}

	table {
		position: absolute;
		top: 50%;
		text-align: center;
	}

	input[type=text] {
		position: relative;
		left: 3%;
	}

	#search {
		width: 80%;
	}

	select {
		-webkit-appearance: none;
		-moz-appearance: none;
		text-indent: 1px;
		text-overflow: '';
		overflow: auto;
		border-radius: 3px;
		margin-left:1.5%; 
		margin-top:2px;
		/*top right bottom left*/
		padding:2% 0 2% 0;
	}


	@media screen 
		and (max-device-width: 1920px)
		{
			#id_severity_level {
			position: relative;
			display: none;
			width: 10%;
			margin-left: -9%;
			text-align: center;

			
			}

			#id_assistance_type {
				position: relative;
				display: none;
				margin-left: -9%;

			}
	}


	@media screen 
		and (max-width: 1367px)
		{
			#id_severity_level {
			position: relative;
			display: none;
			width: 10%;
			margin-left: -9%;
			text-align: center;

			
			}

			#id_assistance_type {
				position: relative;
				display: none;
				margin-left: -9%;

			}
	}

	#message {
		position: absolute;
		top: 23%;
		color: #000000;
		z-index: 1;
		/*top right bottom left*/
		background-color: #FDEF8D;
		margin-left: 1.5%;
		font-size: 22px;
		border-radius: 4px;
		padding: 5px;
		z-index: -1;
		display: none;
		width: 97%;
	}

	.case-detail {
		border: none;
		background: none;
		cursor: pointer;
	}

	.tooltip1 {
		display: none;
		background-color: #ABDEEA;
		color: #000000;
		position: absolute;
		font-size: 10px;
		width: 10%;
		z-index: 1;
		text-align: center;
		right: 3%;
		border-radius: 2px;
	}

	.case-detail:hover .tooltip1 {
		display: block;
	}

	th {
		cursor: pointer;
	}
</style>



<body>
	<div class="modal fade" tabindex="-1" role="dialog" id="modal">
		<div class="modal-dialog" role="document">
			<div class="modal-content"></div>
		</div>
	</div>

	<div class="container-fluid">
	<form id="filter" method="GET">
		<div class="row" style="margin-top: 2%;">
			<div class="col-md-6">
				<input type="text" class="form-control" placeholder="Please enter the case ID here" name="id" id="id_id" autocomplete="off" style="border:1px solid black;">
			</div>

			<div class="col-md-2 text-right">
				<div class="dropdown">
						<button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Categories
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item" href="#" id="severity" onmouseover="displaySeverity()" onmouseout="hideSeverity()">Severity</a>
							<a class="dropdown-item" href="#" onmouseover="displayAssistance()" onmouseout="hideAssistance()">Type of Assistance Required</a>
						</div>
				</div>
			</div>

			<div class="col-md-2 text-center" >
					<input type="text" name="incident_day" value="" class="datepicker form-control" id="id_incident_day" autocomplete="off" style="border:1px solid black" placeholder="Click to show calendar">
			</div>


			<div class="col-md-2 text-center">
					<button type="submit" class="btn btn-outline-dark" id="search">Search</button>
			</div>	
		</div>

		<div id="assistance-menu">
			<div class="row">
				<div class="col-md-9">
				</div>
				<div class="col-md-3">
				<select name="assistance_type" id="id_assistance_type" size="5" onmouseover="displayAssistance()" onmouseout="hideAssistance()" onchange="showAssistanceMessage()">
						<option value="">----------</option>
						<option value="1">Rescue and Evacuation</option>
						<option value="1003">Emergency Ambulance</option>
						<option value="1004">Fire Fighting </option>
						<option value="1005">Gas Leak Control</option>
				</select>

				<select name="severity" id="id_severity_level" size="5" onmouseover="displaySeverity()" onmouseout="hideSeverity()" onchange="showSeverityMessage()">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
					<option value="5">5</option>

				</select>
			</div>
			</div>
			
		</div>

		<!--popup message for the search filter-->
		<p id="message"> </p>


		<!--popup message for closing case-->
		<div class="modal fade" tabindex="-1" role="dialog" id="modal">
			<div class="modal-dialog" role="document">
				<div class="modal-content"></div>
			</div>
		</div>


		</form>

	{% if incident_list %}

		<table class = "table table-bordered table-hover" id="maintable">
			<thead class="thead-light">
				<tr>
					<th scope="col" onclick="sort(0)">Case ID</th>
					<th scope="col">Type of Assistance Required</th>
					<th scope="col" onclick="sort(2)">Level of Security</th>
					<th scope="col" onclick="sort(3)">Date</th>
					<th scope="col" onclick="sort(4)">Time</th>
					<th scope="col">Location</th>
					<th scope="col">Tools</th>
				</tr>
			</thead>
			{% for incident in filter.qs %}
			<tbody>
			<tr id = "rowid">
				<td>{{ incident.id }}</td>
				<td>{{ incident.assistance_type }}</td>
				<td>{{ incident.severity }}</td>
				{% timezone "Asia/Singapore" %}
				<td>{{ incident.incident_date|date:"d M Y" }}</td>
				<td>{{ incident.incident_date|date:"H:i:s"}}</td>
				{% endtimezone %}
				<td>{{incident.location}}</td>
				<td style="text-align: center;">
					<button class= "case-detail" btn data-id="{% url 'cms:case' incident.pk %}" ><i class="fas fa-eye"></i>
						<span class="tooltip1">Click to view details of case</span>
					</button>
				</td>
			</tr>
			{% empty %}
    			<script>
		    		document.getElementById("message").style.display = "block";
		    		document.getElementById("message").innerHTML = "No Incident found. Please choose a different category or value.";
		    	</script>
			{% endfor %}
			</tbody>
		</table>



	{% else %}
		<p>No incidents are available.</p>
	{% endif %}



	
	</div>
</body>

{% endblock %}


<script>
	$(".case-detail").each(function () {
      $(this).modalForm({formURL: $(this).data('id')});
    });

    $(document).ready(function() {
    	$('.datepicker').datepicker(
		);
	});

	function displayAssistance()
	{
		document.getElementById("id_assistance_type").style.display="block";
	}

	function hideAssistance()
	{
		document.getElementById("id_assistance_type").style.display="none";
	}

	function displaySeverity()
	{
		document.getElementById("id_severity_level").style.display="block";

	}

	function hideSeverity()
	{
		document.getElementById("id_severity_level").style.display="none";
	}
	function showAssistanceMessage()
	{
		var x = document.getElementById("id_assistance_type");
		type = x.options[x.selectedIndex].text;
		document.getElementById("message").style.display = "block";
		document.getElementById("message").innerHTML = ("You've selected to filter by the type of assistance: " + type);
		
	}

	function showSeverityMessage()
	{
		var x = document.getElementById("id_severity_level");
		level = x.options[x.selectedIndex].text;
		document.getElementById("message").style.display = "block";
		document.getElementById("message").innerHTML = ("You've selected to filter by level of severity: " + level);

	}

	
	
	function sort(n){
		table = document.getElementById("maintable");
		rows = table.rows.length; //rows = 11
		switching = true;
		direction = "ascending";


		for (i=1; i < rows-1; i++) 
		{
			for (j=1; j < rows-i; j++) 
			{
				x = table.rows[j].cells[n].innerHTML; //x =10, j=1
				y = table.rows[j+1].cells[n].innerHTML; //y=9, j+1=2

				if( !isNaN(Date.parse(x))){
					x = Date.parse(x);
					y = Date.parse(y);
				}


				if (x > y)
				{
					row = table.insertRow(j); //insert row @ 1
					for (k=0; k < 7; k++) 
					{
						cell = row.insertCell(k);
						cell.innerHTML = table.rows[j+2].cells[k].innerHTML;
					}
					document.getElementById("maintable").deleteRow(j+2);
				}

			}
		}
	}


		/*if (shouldSwitch)
		{
			row = table.insertRow(i);
			for (j=0; j < 7; j++)
			{
				cell = row.insertCell(j);
				cell.innerHTML = table.rows[i+2].cells[j].innerHTML;
			}
			document.getElementById("maintable").deleteRow(i+2);
		}*/

</script>
</html>

cms/templates/cms/createincident.html
{% include "cms/nav bar.html" %}
<!DOCTYPE html>
<html lang="en">
{% load widget_tweaks %}


<head>
  {% load staticfiles %}
</head>

<body>
  <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
</body>


<div class="container">
  <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <h2>Add New Case</h2>
  <br>
  <form method="post" action="/cms/create-incident/">
  	{% csrf_token %}
  	{% for hidden_field in form.hidden_fields %}
		{{ hidden_field }}
		{% endfor %}

		{% if form.non_field_errors %}
		<div class="alert alert-danger" role="alert">
			{% for error in form.non_field_errors %}
			{{ error }}
			{% endfor %}
		</div>
		{% endif %}
	    <div class="form-row">
	      <div class="col">
	        {% for hidden_field in form.hidden_fields %}
	        {{ hidden_field }}
	        {% endfor %}
	        {{ form.incident_type.label_tag }}
	        {% render_field form.incident_type class="form-control" %}
	      </div>
	      <div class="col">
	        {{ form.assistance_type.label_tag }}
	        {% render_field form.assistance_type class="form-control" %}
	      </div>
	      <div class="col">
	        {{ form.severity.label_tag }}
	        {% render_field form.severity class="form-control" %}
	      </div>
	    </div>
	    <div class="form-row">
	      <div class="col">
	        {{ form.caller.label_tag }}
	        {% render_field form.caller class="form-control" %}
	      </div>
	      <div class = 'col'>
	        <label for = 'mobile  number'>Mobile Number:</label>
	        {% render_field form.mobile_number class="form-control" %}
		  </div>
		</div>
	   	<br>
	    <div>
	      {% render_field form.street_name class="form-control mr-2" %}
	    </div>
	    <br>
	    <div class="form-row">
	      <div class="col">
	        {% render_field form.apartment_number class="form-control mr-2" %}
	      </div>
	      <div class="col">
	        {% if form.postal_code.errors %}
			{% render_field form.postal_code class="form-control is-invalid" %}
			{% for error in form.postal_code.errors %}
			<div class="invalid-feedback">
				{{ error }}
			</div>
			{% endfor %}
			{% else %}
			{% render_field form.postal_code class="form-control mr-2" %}
			{% endif %}
	      </div>
	    </div>
	    <br>

	    <div>
	      <p class="text-left">
	        <button class="btn btn-primary" type="submit"  name="Submit Case">Submit Case</button>
	      </p>
	    </div>


  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
        $("#id_postal_code").attr('placeholder', '{{form.postal_code.label}}');
        $("#id_street_name").attr('placeholder', '{{form.street_name.label}}');
        $("#id_apartment_number").attr('placeholder', '{{form.apartment_number.label}}');
    });
</script>

cms/templates/cms/nav bar.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Crisis Management System</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" shrink-to-fit="no">
	{% load staticfiles %}
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}" type='text/css' />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
		integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
		
</head>

<style>
	.container-fluid {
		font-family: 'Roboto Condensed', sans-serif;
	}
	.close {
		color: #FFFFFF;
		position: absolute;
		bottom: 2%;
		font-size: 25px;
		margin-left: 45%;
	}

	.close:hover {
		color: white;
	}

	.sidenav {
		height: 100%;
		width: 0;
		position: fixed;
		z-index: 1;
		top: 0;
		left: 0;
		background-color: #000;
		overflow-x: hidden;
		transition: 0.5s;
		padding-top: 60px;
	}

	.sidenav a {
		text-decoration: none;
		position: relative;
		font-size: 25px;
		color: #A3A3A3;
		display: block;
		transition: 0.3s;
		top: -30px;
		border-bottom: 1px solid;
		border-bottom-color: #50514F;
		padding: 10px;
	}

	.sidenav a:hover {
		color: #FFFFFF;
	}

	@media screen and (max-height: 450px) {
		.sidenav {
			padding-top: 15px;
		}

		.sidenav a {
			font-size: 18px;
		}
	}

	h4 {
		color: #FFFFFF;
		position: relative;
		bottom: 10%;
		text-align: left;
		border-bottom: 1px solid;
		border-bottom-color: #50514F;
		/*top right bottom left*/
		padding: 10px 10px 10px 3px;
		font-size: 33px;
	}

	.dummy {
		max-height: 0%;
		position: relative;
		top: -30px;
	}

	#logo {
		width: 15%;
		position: absolute;
		padding: 0;
		top: -110%;
		left: -5%;
	}

	nav a {
		color: white;
		font-size: 20px;
		padding: 0px;
	}

	nav a:hover {	
		color: #A3A3A3;
	}

	.navbar-toggler {
		border: 1px solid black;
	}

	.container-fluid {
		padding: 0;
	}

	.logout:hover {
		text-decoration: none;
	}

	#navbar {
		background-color: #000000;
	}
</style>
</head>

<body>
	<div class="container-fluid">
		<!--links-->
		<div id="sidenavid" class="sidenav">
			<h4>Navigation</h4>
			<!---comment-->
			<div class="dummy">
				<a href="{% url 'cms:closed' %}">View all closed cases</a>
				<a href="{% url 'cms:home' %}">View all active cases</a>
				<a href="{% url 'cms:view-map' %}">View map</a>
				<a href="{% url 'cms:create-incident' %}">Submit Case</a>
			</div>
			<button type="button" onclick="closeNav()" class="close" aria-label="close">
				<i class="fas fa-arrow-left" style="color: white;"></i>
			</button>

		</div>

		<!--navbar-->
		<nav class="navbar navbar-dark" id="navbar">
			<div class="col-sm-1 text-center">

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
					aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon" onclick="openNav()"></span>
				</button>
			</div>

			<div class="col-md-9 text-left">

				<a class="navbar-brand" href="{% url 'cms:home' %}">
					<img src="{% static 'cms/dfcg.png' %}" class="img-responsive center-block" id="logo" >
				</a>
			</div>

			<div class="col-md-2">
				<a href="{% url 'cms:login' %}" style="float:right;" class="logout">Logout</a>
			</div>
		</nav>

		<main role="main">
			{% block content %} {% endblock %}
		</main>
	</div>
</body>
<script>
	function openNav() {
		document.getElementById("sidenavid").style.width = "250px";
	}

	function closeNav() {
		document.getElementById("sidenavid").style.width = "0px";
	}


</script>

cms/templates/cms/success_sms.html
{% include "cms/nav bar.html" %}

<!DOCTYPE html>
<html>
<head>
	<title>CMS</title>
</head>

<style>

</style>
<body>
	<div class ="container-fluid">
		<div class="jumbotron text-center">
      	<h1 class="display">Thank you for your patience</h1>
      	<p class="lead">You have succesfully notify the relevant agencies</p>
      	<a class="btn btn-primary btn-lg" href="{% url 'cms:home' %}">Return home</a>
 		</div>
	</div>
</body>
</html>